### ISSUE TITLE
`[TdJsonClient] received invalid JSON`

### ISSUE THREAD

**Issue by AndrewLaneX** [airgram/airgram#114]
**Issue type:**

- [ ] question
- [x] bug report
- [ ] feature request
- [ ] documentation issue

**Airgram version:**

- [x] `latest`
- [ ] `@next`
- [ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I create two or more instances, I would get [`[TdJsonClient] received invalid JSON`](https://github.com/airgram/airgram/blob/8132fb474b0140c32f40ff9460fd1f5cb55911e1/packages/airgram/src/components/TdClient.ts#L165) randomly for a random client.

```
Error: [TdJsonClient] received invalid JSON
    at TdClient.<anonymous> (/home/.../code/.../node_modules/airgram/components/TdClient.js:185:31)
    at step (/home/.../code/.../node_modules/airgram/components/TdClient.js:44:23)
    at Object.next (/home/.../code/.../node_modules/airgram/components/TdClient.js:25:53)
    at fulfilled (/home/.../code/.../node_modules/airgram/components/TdClient.js:16:58)
```

<details>
<summary>TDLib logs</summary>

```
[ 3][t 4][1592777109.792986870][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.6.0"
  }
}
[ 3][t 4][1592777109.793097496][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}
[ 3][t 0][1592777109.793555975][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 3][t 0][1592777109.793600321][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 0x7efed81019a0
[ 3][t 0][1592777109.793906689][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 3][t 0][1592777109.796537638][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 3][t 7][1592777109.796576500][Td.cpp:4707][#2][!Td][&td_requests]     Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.6.0"
  }
}
[ 3][t 0][1592777109.796605587][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 0x7efed8101f40
[ 3][t 7][1592777109.796626806][Td.cpp:4707][#2][!Td][&td_requests]     Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}
[ 3][t 0][1592777109.796634197][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 0x7efeb81019a0
[ 3][t 4][1592777109.801430702][Td.cpp:3592][#1][!Td][&td_requests]     Receive request 1: setTdlibParameters {
  parameters = tdlibParameters {
    use_test_dc = false
    database_directory = "db/user1"
    files_directory = ""
    use_file_database = false
    use_chat_info_database = true
    use_message_database = false
    use_secret_chats = false
    api_id = ...
    api_hash = "..."
    system_language_code = "en"
    device_model = "..."
    system_version = "0.1.0"
    application_version = "0.1.0"
    enable_storage_optimizer = false
    ignore_file_names = false
  }
}
[ 3][t 0][1592777109.801518917][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 3][t 4][1592777109.801696777][Binlog.cpp:370][#1][!Td]        Load: init encryption
[ 3][t 4][1592777109.801754713][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitEncryptionKey {
    is_encrypted = true
  }
}
[ 3][t 4][1592777109.801825285][Td.cpp:4722][#1][!Td][&td_requests]     Sending result for request 1: ok {
}
[ 3][t 0][1592777109.801829338][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 0x7efed81084c0
[ 3][t 0][1592777109.801822901][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 3][t 0][1592777109.801862478][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 0x7efeb8101f40
[ 3][t 4][1592777109.802407503][Td.cpp:3592][#1][!Td][&td_requests]     Receive request 2: checkDatabaseEncryptionKey {
  encryption_key = bytes [0] { }
}
[ 3][t 4][1592777109.802516937][Binlog.cpp:370][#1][!Td]        Load: init encryption
[ 3][t 0][1592777109.808230400][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 3][t 0][1592777109.808277369][Client.cpp:276][&td_requests]   End to wait for updates, returning object 1 0x7efed81084e0
[ 3][t 0][1592777109.808512211][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 3][t 7][1592777109.808653593][Td.cpp:3592][#2][!Td][&td_requests]     Receive request 1: setTdlibParameters {
  parameters = tdlibParameters {
    use_test_dc = false
    database_directory = "db/user2"
    files_directory = ""
    use_file_database = false
    use_chat_info_database = true
    use_message_database = false
    use_secret_chats = false
    api_id = ...
    api_hash = "..."
    system_language_code = "en"
    device_model = "..."
    system_version = "0.1.0"
    application_version = "0.1.0"
    enable_storage_optimizer = false
    ignore_file_names = false
  }
}
[ 3][t 7][1592777109.808843613][Binlog.cpp:370][#2][!Td]        Load: init encryption
[ 3][t 7][1592777109.808878899][Td.cpp:4707][#2][!Td][&td_requests]     Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitEncryptionKey {
    is_encrypted = true
  }
}
[ 3][t 0][1592777109.808913231][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 0x7efeb8108410
[ 3][t 7][1592777109.808936357][Td.cpp:4722][#2][!Td][&td_requests]     Sending result for request 1: ok {
}
[ 3][t 0][1592777109.810259104][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 2][t 4][1592777109.812696218][TdDb.cpp:315][#1][!Td]  Got PRAGMA user_version = 11
[ 2][t 4][1592777109.813631058][DialogDb.cpp:93][#1][!Td]       Drop dialog_db [version:11][current_db_version:11]
[ 2][t 4][1592777109.813720465][MessagesDb.cpp:171][#1][!Td]    Drop message database [version:11][current_db_version:11]
[ 3][t 4][1592777109.813736200][FileDb.cpp:44][#1][!Td] Init file database [version:11]
[ 3][t 4][1592777109.814780951][Td.cpp:4319][#1][!Td]   Successfully inited database in [database_directory:/home/.../code/.../db/user1/] and [files_directory:/home/.../code/.../db/user1/]
[ 4][t 4][1592777109.814845324][Global.cpp:122][#1][!Td]        LOAD: [server_time_difference:1592706723.575144]
[ 3][t 4][1592777109.814864635][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "unix_time"
  value = optionValueInteger {
    value = 1592777109
  }
}
[ 3][t 7][1592777109.814871073][Td.cpp:3592][#2][!Td][&td_requests]     Receive request 2: checkDatabaseEncryptionKey {
  encryption_key = bytes [0] { }
}
[ 3][t 0][1592777109.814921141][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 0x7efed811cdd0
[ 3][t 7][1592777109.814998865][Binlog.cpp:370][#2][!Td]        Load: init encryption
[ 3][t 4][1592777109.815104246][NetQueryDispatcher.cpp:286][#1][!Td]    [main_dc_id:1]
[ 4][t 4][1592777109.815402031][UpdatesManager.cpp:941][#1][!Td]        Init: 13 0 1592777102
[ 3][t 4][1592777109.815422773][UpdatesManager.cpp:215][#1][!Td][&get_difference]       -----BEGIN GET DIFFERENCE----- from init_state
[ 3][t 4][1592777109.815446615][UpdatesManager.cpp:139][#1][!Td][&get_difference]       [pts:13][qts:0][date:1592777102]
[ 4][t 4][1592777109.815465689][utils.cpp:21][#1][!Td]  Create storer for updates_getDifference {
  flags = 0
  pts = 13
  date = 1592777102
  qts = 0
}
[ 3][t 4][1592777109.815502167][NetQuery.h:347][#1][!Td]        [Query:[id:65536][tl:0x25939651][state:Query]]
[ 3][t 4][1592777109.815522909][Td.cpp:3739][#1][!Td][&net_query]       Send [Query:[id:65536][tl:0x25939651][state:Query]] to dispatcher
[ 3][t 4][1592777109.815538168][NetQuery.h:239][#1][!Td][&net_query]    [Query:[id:65536][tl:0x25939651][state:Query]] [debug:Td: send to NetQueryDispatcher]
[ 3][t 4][1592777109.815553665][NetQuery.h:239][#1][!Td][&net_query]    [Query:[id:65536][tl:0x25939651][state:Query]] [debug:dispatch]
[ 2][t 4][1592777109.815571785][AuthDataShared.cpp:109][#1][!Td]        DcId{1} [auth_key_id:7834107137752632519][state:OK][created_at:1592435663.000000]
[ 3][t 4][1592777109.815594912][NetQuery.h:239][#1][!Td][&net_query]    [Query:[id:65536][tl:0x25939651][state:Query]] [debug:sent to main session multi proxy DcId{1}]
[ 3][t 4][1592777109.815634251][ConnectionCreator.cpp:1018][#1][!ConnectionCreator]     SAVE DcOptions{[DcOption:DcId{1}[ip:149.154.175.57][port:443][secret_len:0][flags:]], [DcOption:DcId{1}[ip:149.154.175.50][port:443][secret_len:0][flags:(Static)]], [DcOption:DcId{1}[ip:2001:b28:f23d:f001::a][port:443][secret_len:0][flags:(IPv6)]], [DcOption:DcId{2}[ip:149.154.167.50][port:443][secret_len:0][flags:]], [DcOption:DcId{2}[ip:149.154.167.51][port:443][secret_len:0][flags:(Static)]], [DcOption:DcId{2}[ip:149.154.167.151][port:443][secret_len:0][flags:(MediaOnly)]], [DcOption:DcId{2}[ip:2001:67c:4e8:f002::a][port:443][secret_len:0][flags:(IPv6)]], [DcOption:DcId{2}[ip:2001:67c:4e8:f002::b][port:443][secret_len:0][flags:(MediaOnly)(IPv6)]], [DcOption:DcId{3}[ip:149.154.175.100][port:443][secret_len:0][flags:]], [DcOption:DcId{3}[ip:149.154.175.100][port:443][secret_len:0][flags:(Static)]], [DcOption:DcId{3}[ip:2001:b28:f23d:f003::a][port:443][secret_len:0][flags:(IPv6)]], [DcOption:DcId{4}[ip:149.154.167.91][port:443][secret_len:0][flags:]], [DcOption:DcId{4}[ip:149.154.167.91][port:443][secret_len:0][flags:(Static)]], [DcOption:DcId{4}[ip:2001:67c:4e8:f004::a][port:443][secret_len:0][flags:(IPv6)]], [DcOption:DcId{4}[ip:149.154.165.120][port:443][secret_len:0][flags:(MediaOnly)]], [DcOption:DcId{4}[ip:2001:67c:4e8:f004::b][port:443][secret_len:0][flags:(MediaOnly)(IPv6)]], [DcOption:DcId{5}[ip:2001:b28:f23f:f005::a][port:443][secret_len:0][flags:(IPv6)]], [DcOption:DcId{5}[ip:91.108.56.193][port:443][secret_len:0][flags:]], [DcOption:DcId{5}[ip:91.108.56.193][port:443][secret_len:0][flags:(Static)]]}
[ 3][t 4][1592777109.815744400][ConfigManager.cpp:761][#1][!Recoverer][&config_recoverer]       Successfully connected
[ 3][t 4][1592777109.815761805][ConfigManager.cpp:831][#1][!Recoverer][&config_recoverer]       Wakeup NEVER
[ 4][t 4][1592777109.815776348][utils.cpp:21][#1][!ConfigManager]       Create storer for help_getConfig {
}
[ 3][t 4][1592777109.815795183][NetQuery.h:347][#1][!ConfigManager]     [Query:[id:131072][tl:0xc4f9186b][state:Query]]
[ 3][t 3][1592777109.815785646][ResourceManager.cpp:136][#1][!UploadResourceManager]    [unused:2097152]
[ 3][t 4][1592777109.815809727][NetQuery.h:239][#1][!ConfigManager][&net_query] [Query:[id:131072][tl:0xc4f9186b][state:Query]] [debug:dispatch]
[ 3][t 4][1592777109.815834284][NetQuery.h:239][#1][!ConfigManager][&net_query] [Query:[id:131072][tl:0xc4f9186b][state:Query]] [debug:sent to main session multi proxy DcId{1}]
[ 4][t 4][1592777109.815897465][TopDialogManager.cpp:543][#1][!TopDialogManager]        Init is enabled: true
[ 3][t 4][1592777109.815917969][StorageManager.cpp:310][#1][!StorageManager]    No next file gc is scheduled
[ 3][t 4][1592777109.815932989][StorageManager.cpp:233][#1][!StorageManager]    Loaded fast storage statistics with 0 files of total size 0
[ 3][t 4][1592777109.815968275][NotificationManager.cpp:4040][#1][!NotificationManager][&notifications] Begin to process 0 binlog events
[ 3][t 4][1592777109.815983057][NotificationManager.cpp:4087][#1][!NotificationManager][&notifications] Finish processing binlog events
[ 3][t 4][1592777109.816003799][ConnectionCreator.cpp:543][#1][!ConnectionCreator][&connections]        Receive network flag true with generation 1
[ 3][t 4][1592777109.816017866][ConnectionCreator.cpp:548][#1][!ConnectionCreator][&connections]        Set proxy query token to 0: 0 1
[ 3][t 4][1592777109.816030979][ConnectionCreator.cpp:567][#1][!ConnectionCreator][&connections]        Receive online flag false
[ 3][t 4][1592777109.816053391][ConfigManager.cpp:761][#1][!Recoverer][&config_recoverer]       Successfully connected
[ 3][t 4][1592777109.816067219][ConfigManager.cpp:831][#1][!Recoverer][&config_recoverer]       Wakeup NEVER
[ 3][t 4][1592777109.816080332][ConfigManager.cpp:581][#1][!Recoverer][&config_recoverer]       ON CONNECTING true
[ 3][t 4][1592777109.816092968][ConfigManager.cpp:759][#1][!Recoverer][&config_recoverer]       Failed to connect for 0.000002
[ 3][t 4][1592777109.816107988][ConfigManager.cpp:828][#1][!Recoverer][&config_recoverer]       Wakeup in 20.0s
[ 2][t 4][1592777109.816123009][SessionMultiProxy.cpp:121][#1][!SessionMultiProxy:1:main]       [session_count:1]
[ 3][t 4][1592777109.816138744][NetQuery.h:239][#1][!SessionMultiProxy:1:main][&net_query]      [Query:[id:65536][tl:0x25939651][state:Query]] [debug:SessionMultiProxy:1:main: send to proxy #0]
[ 2][t 4][1592777109.816185951][Session.cpp:145][#1][!SessionProxy:1:main]      Generate new session_id 2482055318216369051 for auth key 7834107137752632519 for main DC1
[ 3][t 4][1592777109.816203356][NetQuery.h:239][#1][!SessionProxy:1:main][&net_query]   [Query:[id:65536][tl:0x25939651][state:Query]] [debug:SessionProxy:1:main: sent to session]
[ 3][t 4][1592777109.816219330][NetQuery.h:239][#1][!Session:1:main][&net_query]        [Query:[id:65536][tl:0x25939651][state:Query]] [debug:Session: received from SessionProxy]
[ 3][t 4][1592777109.816233397][Session.cpp:234][#1][!Session:1:main][&net_query]       Got query [Query:[id:65536][tl:0x25939651][state:Query]]
[ 3][t 4][1592777109.816247225][NetQuery.h:239][#1][!Session:1:main][&net_query]        [Query:[id:65536][tl:0x25939651][state:Query]] [debug:Session: pending]
[ 3][t 4][1592777109.816261292][NetQuery.h:239][#1][!SessionMultiProxy:1:main][&net_query]      [Query:[id:131072][tl:0xc4f9186b][state:Query]] [debug:SessionMultiProxy:1:main: send to proxy #0]
[ 3][t 4][1592777109.816280842][NetQuery.h:239][#1][!SessionProxy:1:main][&net_query]   [Query:[id:131072][tl:0xc4f9186b][state:Query]] [debug:SessionProxy:1:main: sent to session]
[ 3][t 4][1592777109.816301823][ConnectionCreator.cpp:615][#1][!ConnectionCreator][&connections]        Request connection for [client:0xe3587d040fb8b39b] to DcId{1} [allow_media_only:false]
[ 3][t 4][1592777109.816317797][ConnectionCreator.cpp:814][#1][!ConnectionCreator][&connections]        In client_loop: [client:0xe3587d040fb8b39b]
[ 4][t 4][1592777109.816335917][DcOptionsSet.cpp:50][#1][!ConnectionCreator]    Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 4][1592777109.816354752][ConnectionCreator.cpp:711][#1][!ConnectionCreator]      Create: [149.154.175.57:443] to DcId{1}
[ 3][t 4][1592777109.816449165][ConnectionCreator.cpp:786][#1][!ConnectionCreator][&connections]        Create new direct connection [149.154.175.57:443] to DcId{1} from [192.168.1.10:47520]
[ 4][t 4][1592777109.816476107][Session.cpp:1336][#1][!Session:1:main]  Wakeup after 1000.000000
[ 3][t 4][1592777109.816492319][NetQuery.h:239][#1][!Session:1:main][&net_query]        [Query:[id:131072][tl:0xc4f9186b][state:Query]] [debug:Session: received from SessionProxy]
[ 3][t 4][1592777109.816509247][Session.cpp:234][#1][!Session:1:main][&net_query]       Got query [Query:[id:131072][tl:0xc4f9186b][state:Query]]
[ 3][t 4][1592777109.816523552][NetQuery.h:239][#1][!Session:1:main][&net_query]        [Query:[id:131072][tl:0xc4f9186b][state:Query]] [debug:Session: pending]
[ 3][t 4][1592777109.816551924][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "venue_search_bot_username"
  value = optionValueString {
    value = "foursquare"
  }
}
[ 3][t 4][1592777109.816666126][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "calls_enabled"
  value = optionValueBoolean {
    value = true
  }
}
[ 3][t 0][1592777109.816663980][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 3][t 4][1592777109.816699982][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "animation_search_bot_username"
  value = optionValueString {
    value = "gif"
  }
}
[ 3][t 0][1592777109.816709518][Client.cpp:276][&td_requests]   End to wait for updates, returning object 1 0x7efeb8108430
[ 3][t 4][1592777109.816746235][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "my_id"
  value = optionValueInteger {
    value = ...
  }
}
[ 3][t 0][1592777109.816754103][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 10.000000
[ 3][t 0][1592777109.816782713][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 0x7efed8125060
[ 3][t 4][1592777109.816786051][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "call_packet_timeout_ms"
  value = optionValueInteger {
    value = 10000
  }
}
[ 3][t 4][1592777109.816827774][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "animated_emoji_sticker_set_name"
  value = optionValueString {
    value = "animatedemojies"
  }
}
[ 3][t 4][1592777109.816861868][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "authorization_date"
  value = optionValueInteger {
    value = 1592435672
  }
}
[ 3][t 4][1592777109.816899061][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "forwarded_message_count_max"
  value = optionValueInteger {
    value = 100
  }
}
[ 3][t 4][1592777109.816940069][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "pinned_chat_count_max"
  value = optionValueInteger {
    value = 5
  }
}
[ 3][t 4][1592777109.817003727][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "basic_group_size_max"
  value = optionValueInteger {
    value = 200
  }
}
[ 3][t 4][1592777109.817031384][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "supergroup_size_max"
  value = optionValueInteger {
    value = 200000
  }
}
[ 3][t 4][1592777109.817046881][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "photo_search_bot_username"
  value = optionValueString {
    value = "bing"
  }
}
[ 3][t 4][1592777109.817077398][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "test_mode"
  value = optionValueBoolean {
    value = false
  }
}
[ 3][t 4][1592777109.817104816][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "pinned_archived_chat_count_max"
  value = optionValueInteger {
    value = 100
  }
}
[ 3][t 4][1592777109.817118883][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "favorite_stickers_limit"
  value = optionValueInteger {
    value = 5
  }
}
[ 3][t 4][1592777109.817133665][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "message_text_length_max"
  value = optionValueInteger {
    value = 4096
  }
}
[ 3][t 4][1592777109.817152023][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "message_caption_length_max"
  value = optionValueInteger {
    value = 1024
  }
}
[ 3][t 4][1592777109.817178965][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "expect_blocking"
  value = optionValueBoolean {
    value = false
  }
}
[ 3][t 4][1592777109.817203999][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "t_me_url"
  value = optionValueString {
    value = "https://t.me/"
  }
}
[ 3][t 4][1592777109.817229748][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "call_connect_timeout_ms"
  value = optionValueInteger {
    value = 30000
  }
}
[ 3][t 4][1592777109.817243814][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateAuthorizationState {
  authorization_state = authorizationStateReady {
  }
}
[ 3][t 4][1592777109.817273140][Td.cpp:4722][#1][!Td][&td_requests]     Sending result for request 2: ok {
}
[ 3][t 4][1592777109.817309618][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateSelectedBackground {
  for_dark_theme = false
  background = null
}
[ 3][t 4][1592777109.817325115][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateSelectedBackground {
  for_dark_theme = true
  background = null
}
[ 3][t 4][1592777109.817350388][InlineQueriesManager.cpp:804][#1][!InlineQueriesManager]        Inline query loop
[ 3][t 4][1592777109.817424059][ConnectionCreator.cpp:944][#1][!ConnectionCreator][&connections]        Ready connection (unchecked) 0x7efed81039e0 [rtt:0.0ns] [149.154.175.57:443] to DcId{1} from [192.168.1.10:47520]
[ 3][t 4][1592777109.817462921][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateConnectionState {
  state = connectionStateConnecting {
  }
}
[ 3][t 4][1592777109.817480326][ConnectionCreator.cpp:996][#1][!ConnectionCreator][&connections]        Add ready connection 0x7efed81039e0 for [client:0xe3587d040fb8b39b]
[ 3][t 4][1592777109.817493200][ConnectionCreator.cpp:814][#1][!ConnectionCreator][&connections]        In client_loop: [client:0xe3587d040fb8b39b]
[ 3][t 4][1592777109.817501307][ConnectionCreator.cpp:830][#1][!ConnectionCreator][&connections]        Send to promise [connection:0x7efed81039e0]
[ 3][t 4][1592777109.817516804][Session.cpp:1050][#1][!Session:1:main]  Finished to open connection Session:1:main::Connect::Tcp::[149.154.175.57:443] to DcId{1} from [192.168.1.10:47520]
[ 3][t 4][1592777109.817567348][NetQuery.h:239][#1][!Session:1:main][&net_query]        [Query:[id:65536][tl:0x25939651][state:Query]] [debug:Session: trying to send to mtproto::connection]
[ 3][t 4][1592777109.817586184][NetQuery.h:239][#1][!Session:1:main][&net_query]        [Query:[id:65536][tl:0x25939651][state:Query]] [debug:Session: send to mtproto::connection]
[ 3][t 4][1592777109.817596912][Session.cpp:929][#1][!Session:1:main][&net_query]       Send query to connection [Query:[id:65536][tl:0x25939651][state:Query]] [msg_id:0x5eefd9958f1b41d0][invoke_after:0x0000000000000000]
[ 3][t 4][1592777109.817611217][NetQuery.h:239][#1][!Session:1:main][&net_query]        [Query:[id:131072][tl:0xc4f9186b][state:Query]] [debug:Session: trying to send to mtproto::connection]
[ 3][t 4][1592777109.817623138][NetQuery.h:239][#1][!Session:1:main][&net_query]        [Query:[id:131072][tl:0xc4f9186b][state:Query]] [debug:Session: send to mtproto::connection]
[ 3][t 4][1592777109.817631960][Session.cpp:929][#1][!Session:1:main][&net_query]       Send query to connection [Query:[id:131072][tl:0xc4f9186b][state:Query]] [msg_id:0x5eefd9958f1def78][invoke_after:0x0000000000000000]
[ 4][t 4][1592777109.817692280][Session.cpp:1336][#1][!Session:1:main]  Wakeup after 59.999961
user2: Error: [TdJsonClient] received invalid JSON
    at TdClient.<anonymous> (/home/.../code/.../node_modules/airgram/components/TdClient.js:185:31)
    at step (/home/.../code/.../node_modules/airgram/components/TdClient.js:44:23)
    at Object.next (/home/.../code/.../node_modules/airgram/components/TdClient.js:25:53)
    at fulfilled (/home/.../code/.../node_modules/airgram/components/TdClient.js:16:58)
```

</details>

**Comment by esindger** [comment]
Is this a recurring error?

**Comment by AndrewLaneX** [comment]
Yeah.

**Comment by AndrewLaneX** [comment]
Not sure if this is a proper fix, but this fix it.

```diff
diff --git a/packages/airgram/src/components/TdClient.ts b/packages/airgram/src/components/TdClient.ts
index 2a1ca06..c8848b3 100644
--- a/packages/airgram/src/components/TdClient.ts
+++ b/packages/airgram/src/components/TdClient.ts
@@ -157,7 +157,7 @@ export class TdClient {
   private async receive (): Promise<NativeTdObject | null> {
     try {
       const data: string | null = await this.tdlib.receive(this.tdClient, this.timeout)
-      if (data === null) {
+      if (data === null || data === '') {
         return null
       }
       return JSON.parse(data, this.deserialize)
```

**Comment by esindger** [comment]
Ok, thank you.

Will be fixed it in the next release.

**Comment by AndrewLaneX** [comment]
Seems like that isn't the case. I got the error again with `data = 'p\f'`.

**Comment by esindger** [comment]
Do you receive broken data from TDLib?
Can you provide your exactly versions of Node.js, TDLib and ffi-napi?

**Comment by AndrewLaneX** [comment]
Node: `v12.16.1`
TDLib: `v1.6.0`
ffi-napi: `v3.0.1`

**Comment by esindger** [comment]
Seems like corrupted data is coming from TDLib. I couldn't reproduce this error. Please try to use different database folder. If it does not help it is better to create an issue in [TDLib repository](https://github.com/tdlib/td/issues) and attach log with verbosity level 100.

**Comment by AndrewLaneX** [comment]
I already use a different directory for each instance.

**Comment by safead** [comment]
same here:

```
(node:932362) UnhandledPromiseRejectionWarning: Error: [TdJsonClient] received invalid JSON
    at TdClient.<anonymous> (/var/_telegram_backend/node_modules/airgram/components/TdClient.js:186:31)
    at step (/var/_telegram_backend/node_modules/airgram/components/TdClient.js:44:23)
    at Object.next (/var/_telegram_backend/node_modules/airgram/components/TdClient.js:25:53)
    at fulfilled (/var/_telegram_backend/node_modules/airgram/components/TdClient.js:16:58)

```

**Comment by esindger** [comment]
Do you have multiple clients?

**Comment by safead** [comment]
> Do you have multiple clients?

Yes, we do. Btw, what is the best practice to act with a lot of client instances at the same server? Using workers (each worker with the TDLib instance), or using child_process? Because starting 10 clients in the main Node.js thread causing this error more frequently. Please advise...

**Comment by AndrewLaneX** [comment]
@safead for now, I create a copy of the tdlib build file for every instance.

**Comment by levlam** [comment]
@esindger The latest TDLib version has new JSON interface which allows to receive updates and responses for all TDLib instances in the same thread. The new interface is supposed to replace current JSON interface in the future. You can find the interface's documentation in https://github.com/tdlib/td/blob/966621376b87fda5b9eb29dd2f4da7732bf1c654/td/telegram/td_json_client.h#L97. Does the new interface help to solve node-ffi limitations?

**Comment by esindger** [comment]
Good news, I will check it.

**Comment by esindger** [comment]
@levlam Done. I have not encountered any issues for 2 clients working simultaneously.

@AndrewLaneX, @safead can you check how multi clients work in your case?
Requirements:  Airgram 3.2.1, TDLib 1.6.9

**Comment by AndrewLaneX** [comment]
@esindger it works with one, but I get an error with 2 or more:

```
[ 3][t 4][1603853772.186706066][Td.cpp:4557][#1][!Td][&td_requests]	Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.6.9"
  }
}
(node:203528) UnhandledPromiseRejectionWarning: Error: [TdProxy] updates handler for the client 1 not found. Missed update: {"_":"updateAuthorizationState","authorizationState":{"_":"authorizationStateWaitTdlibParameters"}}
    at TdJsonClient.<anonymous> (node_modules/airgram/components/TdJsonClient.js:197:38)
    at step (node_modules/airgram/components/TdJsonClient.js:53:23)
    at Object.next (node_modules/airgram/components/TdJsonClient.js:34:53)
    at node_modules/airgram/components/TdJsonClient.js:28:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/airgram/components/TdJsonClient.js:24:12)
    at TdJsonClient.handleUpdate (node_modules/airgram/components/TdJsonClient.js:189:16)
    at TdJsonClient.<anonymous> (node_modules/airgram/components/TdJsonClient.js:177:55)
    at step (node_modules/airgram/components/TdJsonClient.js:53:23)
    at Object.next (node_modules/airgram/components/TdJsonClient.js:34:53)
(node:203528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:203528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[ 0][t 0][1603853772.195518970][Client.cpp:271]	Receive is called after Client destroy, or simultaneously from different threads
Aborted (core dumped)
```

**Comment by levlam** [comment]
@AndrewLaneX This is a race condition in the new design: https://github.com/tdlib/td/issues/1242. We will change the new TDLib API to mitigate its possibility.

**Comment by esindger** [comment]
@AndrewLaneX, fixed in `v3.2.2`

**Comment by levlam** [comment]
@esindger In the latest TDLib version we replaced the function `td_create_client` with the function `td_create_client_id`. It assigns client ID, but defers client creation until first request is sent to it. This mitigates the race, but requires sending a dummy request before `updateAuthorizationState` and other updates can be received. You can send, for example, a `getOption('version')` or a `setAlarm(0.0)` request.

This interface is supposed to become a part of TDLib 1.7.0 release soon.
