### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by Liiion911** [airgram/airgram#144]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ ] `latest`
[ ] `@next`
[x] `3.0.2`

**Steps to reproduce or a small repository showing the problem:**

Hello!

I am switching from TDL to Airgram and get this error:

```
1|hr  | /home/hr/node_modules/airgram/components/TdProvider.js:7
1|hr  |         return extendStatics(d, b);
1|hr  |                ^
1|hr  | TypeError: Object prototype may only be an Object or null: undefined
1|hr  |     at setPrototypeOf (<anonymous>)
1|hr  |     at extendStatics (/home/hr/node_modules/airgram/components/TdProvider.js:7:16)
1|hr  |     at __extends (/home/hr/node_modules/airgram/components/TdProvider.js:10:9)
1|hr  |     at /home/hr/node_modules/airgram/components/TdProvider.js:66:5
1|hr  |     at Object.<anonymous> (/home/hr/node_modules/airgram/components/TdProvider.js:128:2)
1|hr  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
1|hr  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
1|hr  |     at Module.load (internal/modules/cjs/loader.js:599:32)
1|hr  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
1|hr  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

What am I doing wrong?

**Comment by Liiion911** [comment]
Fixed.
Install nodejs v14
Install airgram 4.0.0
Build tdlib 1.7.0
