### ISSUE TITLE
throws Error: no such file or directory, open '/home/xyz/myarigram/libtdjson.so'

### ISSUE THREAD

**Issue by byteshiva** [airgram/airgram#173]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x ] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have followed the steps given in airgram, After installation, I get the below error.

Code:
```
import { Airgram, Auth, prompt, toObject } from 'airgram'

const airgram = new Airgram({
  apiId: process.env.APP_ID,
  apiHash: process.env.APP_HASH
})

airgram.use(new Auth({
  code: () => prompt(`Please enter the secret code:\n`),
  phoneNumber: () => prompt(`Please enter your phone number:\n`)
}))

void (async () => {
  const me = toObject(await airgram.api.getMe())
  console.log(`[me]`, me)
})

// Getting all updates
airgram.use((ctx, next) => {
  if ('update' in ctx) {
    console.log(`[all updates][${ctx._}]`, JSON.stringify(ctx.update))
  }
  return next()
})

// Getting new messages
airgram.on('updateNewMessage', async ({ update }, next) => {
  const { message } = update
  console.log('[new message]', message)
  return next()
})

```

**Error**:
```ts

node index.js 
node:fs:506
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/home/xyz/myarigram/libtdjson.so'
    at Object.openSync (node:fs:506:3)
    at readFileSync (node:fs:402:35)
    at new DynamicLibrary (/home/xyz/myarigram/node_modules/ffi-napi/lib/dynamic_library.js:68:23)
    at Object.Library (/home/xyz/myarigram/node_modules/ffi-napi/lib/library.js:47:10)
    at new TdJsonClient (/home/xyz/myarigram/node_modules/airgram/components/TdJsonClient.js:86:27)
    at new Airgram (/home/xyz/myarigram/node_modules/airgram/Airgram.js:50:116)
    at file:///home/xyz/myarigram/index.js:7:17
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/xyz/myarigram/libtdjson.so'
}

```

**Comment by Domingowen** [comment]
you need to copy "libtdjson.so" it to your project folder root.

**Comment by stav** [comment]
cp  tdlib/td/build/libtdjson.so.1.7.9  airgram/examples/getting-started/libtdjson.so
