### ISSUE TITLE
Dynamic Linking Error on Getting started example

### ISSUE THREAD

**Issue by javierarocena** [airgram/airgram#204]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

Hi there, Im trying run Airgram following the getting-started example:
1. Clone repository
2. Install dependencies
3. Open the example directory
4. Run example

But when I run "yarn run dev" I got this error:

```
Error: Dynamic Linking Error: dlopen(/Users/mntlrndr/localProject/TELEGRAM/airgram/examples/getting-started/libtdjson.dylib, 2): image not found
    at new DynamicLibrary (/Users/mntlrndr/localProject/TELEGRAM/airgram/node_modules/ffi-napi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/mntlrndr/localProject/TELEGRAM/airgram/node_modules/ffi-napi/lib/library.js:45:14)
    at new TdJsonClient (/Users/mntlrndr/localProject/TELEGRAM/airgram/packages/airgram/src/components/TdJsonClient.ts:65:23)
    at new Airgram (/Users/mntlrndr/localProject/TELEGRAM/airgram/packages/airgram/src/Airgram.ts:31:75)
    at Object.<anonymous> (/Users/mntlrndr/localProject/TELEGRAM/airgram/examples/getting-started/src/index.ts:8:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/mntlrndr/localProject/TELEGRAM/airgram/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/mntlrndr/localProject/TELEGRAM/airgram/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

Screenshot:
![image](https://user-images.githubusercontent.com/33159867/166260246-edb3cd33-7b71-456a-a2c7-4fe5e527ee11.png)

Any ideas? Thanks :)

**Comment by nmrusso** [comment]
Hi!

I don't have a Mac to test it.

Apparently it can't find the library, in the case of Mac it seems that it would be the image.

```ts
  const airgram = new Airgram({
             apiId: xxxxx,
             apiHash: 'xxxxxxxx,
             command: '/projects/app/src/libtdjson.so',
             databaseDirectory: './db',
             logVerbosityLevel: 2
 });
```

In my case I have to put the whole URL.

With this it works perfectly for me.

I have not yet investigated if putting it in a specific place takes it immediately. (I guess yes).

**Comment by s3nPy** [comment]
+1 Getting same error

**Comment by mmdzov** [comment]
+1

**Comment by HardLuckys** [comment]
+1

**Comment by mmdzov** [comment]
Well, the solution is that you need to download the zip file of the latest version of [tdlib.native](https://github.com/ForNeVeR/tdlib.native/releases)

In the next step, put the content of the zip file in the main path of your project. Similar to this [comment](https://github.com/Bannerets/tdl/issues/25#issuecomment-428666231)
