### ISSUE TITLE
Dynamic Linking Error

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#29]
## 🐛  Bug Report

**Current Behavior**
A clear and concise description of the behavior.

It throws dynamic link error

**Input Code**
- REPL or Repo link if applicable

```js
#!/usr/local/bin/node

import { Airgram, Auth, prompt } from 'airgram';

const airgram = new Airgram({ apiId: ****, apiHash: ****});

const auth = new Auth(airgram);

```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

should clean exit

**Environment**
- Airgram version: 1.0.1
- Node/npm version: v10.16.0/6.9.0
- Language: [JavaScript/TypeScript] JS

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

ERROR STACK

```js
nodemon] restarting due to changes...
[nodemon] starting `babel-node src/index.js`
/Users/peter/Program/telegram-airgram/node_modules/ffi-napi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: dlopen(/Users/peter/Program/telegram-airgram/libtdjson.dylib, 2): image not found
    at new DynamicLibrary (/Users/peter/Program/telegram-airgram/node_modules/ffi-napi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/peter/Program/telegram-airgram/node_modules/ffi-napi/lib/library.js:45:14)
    at new TdLib (/Users/peter/Program/telegram-airgram/node_modules/airgram/src/components/TdLib.ts:37:22)
    at new TdProxy (/Users/peter/Program/telegram-airgram/node_modules/airgram/src/components/TdProxy.ts:44:18)
    at new Airgram (/Users/peter/Program/telegram-airgram/node_modules/airgram/src/Airgram.ts:36:20)
    at Object.<anonymous> (/Users/peter/Program/telegram-airgram/src/index.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/Users/peter/Program/telegram-airgram/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (/Users/peter/Program/telegram-airgram/node_modules/pirates/lib/index.js:104:7)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by ktjd123** [comment]
It was mac's problem you can solve it downloading libtdjson.dylib to project folder

**Comment by thedevxen** [comment]
where in the project should I place the lib file?

**Comment by volekerb** [comment]
Problem still exists. I guess it's better to include downloading libtdjson.dylib to project folder somewhere in Readme

**Comment by AndreoliBR** [comment]
I'm facing the same problem but i'm on a windows. Here is the error:

```
C:\www\airgram-example\airgram\node_modules\ffi-napi\lib\dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err);
          ^
Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (C:\www\airgram-example\airgram\node_modules\ffi-napi\lib\dynamic_library.js:74:11)
    at Object.Library (C:\www\airgram-example\airgram\node_modules\ffi-napi\lib\library.js:45:14)
    at new TdJsonClient (C:\www\airgram-example\airgram\packages\airgram\src\components\TdJsonClient.ts:67:23)
    at new Airgram (C:\www\airgram-example\airgram\packages\airgram\src\Airgram.ts:31:75)
    at Object.<anonymous> (C:\www\airgram-example\airgram\examples\getting-started\src\index.ts:7:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (C:\www\airgram-example\airgram\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (C:\www\airgram-example\airgram\node_modules\ts-node\src\index.ts:861:12) 
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

I'm following the example code
