### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#37]
## 🐛  Bug Report

**Current Behavior**

throws error for unexpected token for almost every request at ubuntu 18 (seems not happening at mac)

**Input Code**

```js
await airgram.api
      .getMe()
      .then(async (res) => {
        console.log('logged in : ', res.firstName, res.lastName);
        user.alive = true;
        user.lastUsed = new Date();
        await user.save();
      })
      .catch(async () => {
        console.log('logged in failed : ', user.phoneNumber);
        user.alive = false;
        await user.save();
      });
```

**Error Code**

```js
(node:9667) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token à in JSON at position 0
    at JSON.parse (<anonymous>)
    at TdProxy.<anonymous> (/home/ubuntu/tele/node_modules/airgram/dist/components/TdProxy.js:172:54)
    at step (/home/ubuntu/tele/node_modules/airgram/dist/components/TdProxy.js:43:23)
    at Object.next (/home/ubuntu/tele/node_modules/airgram/dist/components/TdProxy.js:24:53)
    at fulfilled (/home/ubuntu/tele/node_modules/airgram/dist/components/TdProxy.js:15:58)
(node:9667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

```js
(node:9792) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at TdProxy.<anonymous> (/home/ubuntu/tele/node_modules/airgram/dist/components/TdProxy.js:172:54)
    at step (/home/ubuntu/tele/node_modules/airgram/dist/components/TdProxy.js:43:23)
    at Object.next (/home/ubuntu/tele/node_modules/airgram/dist/components/TdProxy.js:24:53)
    at fulfilled (/home/ubuntu/tele/node_modules/airgram/dist/components/TdProxy.js:15:58)
(node:9792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Every time the error log changes

**Expected behavior/code**
should not throw this error

**Environment**
- Airgram version: 1.0.3
- Node/npm version: 6.9.0
- Language: JS

**Possible Solution**
validate JSON

**Comment by airgram** [comment]
```
Unhandled Rejection (SyntaxError): Unexpected token < in JSON at position 0
```
This error can happen if Airgram receive not valid JSON from TDLib. Can you increase verbosity log level and look some additional information?
