### ISSUE TITLE
Resend Authentication Code Error

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#42]
## 🐛  Bug Report

**Current Behavior**
Resend Authentication Code with phone call error

Error msg, duplicate promt

the call is performs perfect but I see an error code

**Input Code**

```js

airgram.on(UPDATE.updateAuthorizationState, async ({ update }, next) => {
    const { authorizationState } = update;
    if (authorizationState._ === AUTHORIZATION_STATE.authorizationStateWaitCode) {
      airgram.api.resendAuthenticationCode().then(() => {
      }).catch(err => {
        console.error(err);
      });
    }
    return next();
  });

  const auth = new Auth(airgram);

  await auth.use({
    code: () => prompt('Enter Code Pls'),
    phoneNumber,
    firstName: generateName(),
    lastName: '',
  });

  await airgram.api.getMe().then((res) => {
    console.log('Logged in user is', res.firstName, res.lastName);
  });

```

the error code is 

```js
{ TDLibError: Authentication code can't be resend
    at TdJsonClient.<anonymous> (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:140:45)
    at step (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:43:23)
    at Object.next (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:24:53)
    at /home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:14:12)
    at TdJsonClient.handleResponse (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:124:16)
    at TdJsonClient.addToStack (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:174:22)
    at TdJsonClient.<anonymous> (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:227:28)
    at step (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:43:23)
    at Object.next (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:24:53)
    at fulfilled (/home/ubuntu/tele/node_modules/airgram/dist/components/TdJsonClient.js:15:58) code: 8, type: 'resendAuthenticationCode', name: 'TDLibError' }
```

**Expected behavior/code**
first promt should be closed and second resended code should be activated.

now it seems both of them is activated

**Environment**
- Airgram version: 1.1.0-0
- Node/npm version: node v10
- Language: JS

**Possible Solution**
Close first prompt and solve error

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ktjd123** [comment]
adding a counter will solve the error part

```js
  let counter = false;

  airgram.on(UPDATE.updateAuthorizationState, async ({ update }, next) => {
    const { authorizationState } = update;
    if (authorizationState._ === AUTHORIZATION_STATE.authorizationStateWaitCode && counter === false) {
      counter = true;
      airgram.api.resendAuthenticationCode().then(() => {
      }).catch(err => {
        console.error(err)
      });
    }
    return next();
  });
```

**Comment by ktjd123** [comment]
and it's not logging in

**Comment by ktjd123** [comment]
the full code i use is @airgram 

```js
import mongoose from 'mongoose';
import { Airgram, Auth, prompt } from 'airgram';
import { UPDATE, AUTHORIZATION_STATE } from 'airgram-api';

import provider from './lib/provider';
import getInput from './lib/getInput';
import generateName from './lib/generateName';

import { User } from './models';

const LOCAL_DB = 'telegram-reader';
const MONGODB_URI = process.env.MONGODB_URI || `mongodb://localhost/${LOCAL_DB}`;
// MongoDB
// mongoose.set('debug', true);
mongoose.Promise = global.Promise;
mongoose.connect(MONGODB_URI, {
  useNewUrlParser: true,
  useCreateIndex: true,
  autoIndex: true,
  useFindAndModify: false,
});
const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));

const main = async () => {
  while (true) {
    const phoneNumber = String(await getInput('Please Enter phone Number'));
    const airgram = new Airgram({
      provider: provider(),
      apiId: *****,
      apiHash: '** * ***',
      databaseDirectory: `./db/${phoneNumber}`,
    });

    let counter = false;

    airgram.on(UPDATE.updateAuthorizationState, async ({ update }, next) => {
      const { authorizationState } = update;
      if (
        authorizationState._ === AUTHORIZATION_STATE.authorizationStateWaitCode
        && counter === false
      ) {
        counter = true;
        await airgram.api
          .resendAuthenticationCode()
          .then(() => {
            console.log('Please get ready to get call');
          })
          .catch(() => {
            console.error('please try with another number');
          });
      }
      return next();
    });

    const auth = new Auth(airgram);
    await auth.use({
      code: () => prompt('Please enter code'),
      phoneNumber,
      firstName: generateName().firstName,
      lastName: generateName().lastName,
    });

    await airgram.api.getMe().then((res) => {
      console.log('logged in user is ', res.firstName, res.lastName);
    });

    await User.findOneAndUpdate(
      { phoneNumber },
      { phoneNumber, alive: true, lastUsed: new Date() },
      { upsert: true },
    );
  }
};

main();

```

**Comment by ktjd123** [comment]
Fixed logging in part with airgram-api fix. but duplicate input part is not fixed yet

**Comment by airgram** [comment]
If you need to cancel previous prompt, try to wrap `prompt` function something like that:

```
let prevPrompt: { resolve: (data: any) => any, reject: (error: Error) => any } | null
auth.use({
  code: () => new Promise((resolve, reject) => {
    if (prevPrompt) {
      prevPrompt.reject(new Error('Expired prompt'))
    }
    prevPrompt = { resolve, reject }

    return prompt('Please enter code')
      .then(resolve, reject)
      .finally(() => prevPrompt = null)
  })
})
```

**Comment by ktjd123** [comment]
Nice code but this doesn't fix the problem it won't cancel previous promt

**Comment by airgram** [comment]
I see. Please check out this code with version `1.1.1`:

```ts
import { Airgram, Auth, prompt, PromptDeferred } from 'airgram'

const auth = new Auth(airgram)

let prevPrompt: PromptDeferred | null
auth.use({
  code: () => prompt('Please enter code', (deferred: PromptDeferred) => {
    if (prevPrompt) {
      prevPrompt.reject(new Error('Expired prompt'))
    }
    prevPrompt = deferred
  })
})
```

**Comment by ktjd123** [comment]
the duplicate input problem is fixed now but not authing problem re-happened @airgram

**Comment by airgram** [comment]
Actually, I am not sure what you do and why you need to resend authorization code. Maybe your approach is not correct. Can you clarify it?

**Comment by ktjd123** [comment]
I want to shorten telegram official app's calling time. building a new telegram app

**Comment by airgram** [comment]
When `Auth` middleware got authorization status `authorizationStateWaitPhoneNumber` and receive phone number, Airgram invokes [`setAuthenticationPhoneNumber`](https://github.com/airgram/airgram-api/blob/master/docs/td-methods.md#apisetauthenticationphonenumber) method. So you should not use `resendAuthenticationCode` immediately. 

Probably, you need to have possibility to set `allowFlashCall` and `isCurrentPhoneNumber` parameters for the `setAuthenticationPhoneNumber` method.

**Comment by ktjd123** [comment]
Thankyou
