### ISSUE TITLE
problems with channels parse

### ISSUE THREAD

**Issue by zhgromov** [airgram/airgram#44]
Someone might have encountered a problem: I need to do a parsing of the telegram history of the channel using airgram and airgram.client.messages.getHistory ({}) in the parameters of which I specify the id and access hash of the desired channel. Part of the channels is processed normally, part of them returns with the error UnhandledPromiseRejectionWarning: RpcError: CODE # 400 CHANNEL_INVALID. Data (id and access hash are 100% correct). On this server crashes. What to do?

```    

const dialogs = await airgram.client.messages.getHistory({
        peer: {_: 'inputPeerChannel', channel_id: 1234***910, access_hash: '123907933***888612'},
        offset: 0,
        limit: 200,
        max_id: 10000000000,
        min_id: 0
    })
```

**Comment by airgram** [comment]
The `CHANNEL_INVALID` error is not an Airgram error. It is coming from Telegram. If you are sure you have access to that channels, you should create an issue in [tdlib repository](https://github.com/tdlib/td/issues).

You need to handle errors to avoid `UnhandledPromiseRejectionWarning` or crashing server:

```typescript
try {
  const dialogs = await airgram.client.messages.getHistory({
        // ...
    })
} catch (error) {
  // Something is wrong
  console.error(error.message)
}
```
 
Also you can catch all unhandled exceptions to prevent of crashing server:

```typescript
airgram.catch((error: Error) => {
  if (error.name === 'TDLibError') {
    console.error('TDLib error:', error)
  } else {
    console.log('Other error:', error)
  }
})
```

**Comment by ktjd123** [comment]
check if you are using tdlib 1.4.0

**Comment by zhgromov** [comment]
This did not help, perhaps because I used the old version of airgram. I tried to run ts-example with the new version and try to get the chat history, but I get errors. Tell me how to get the history of the chat, which is not a member? There is only id in the parameters, access_hash is missing

``` airgram.api.getChatHistory({chatId: 1330724252, limit:10}).then((messages) => {
  console.log(`[Mess] `, JSON.stringify(messages))
})```

What am I doing wrong?

**Comment by valoricDe** [comment]
Hi, I have the same problem, trying to fetch the history via:
```
airgram.api.getChatHistory({
  chatId: channel_id,
  limit: 10,
  offset: 0,
}).then((response) => {
  assertResponse(response)
  console.log(response)
}).catch(console.error)
```
And I get `Error: RequestError`

**Comment by esindger** [comment]
@valoricDe, what is your TDLib version?  Can you provide log output please?

**Comment by valoricDe** [comment]
I use now 1.5.1 and logLevel 3 and the channel chat id `-1001414757191` and the the following 
```
...
[ 3][t 4][1575119222.229680300][Td.cpp:3548][#1][!Td][&td_requests]	Receive request 4: getChatHistory {
  chat_id = -1001414757191
  from_message_id = 0
  offset = 0
  limit = 10
  only_local = false
}
[ 3][t 0][1575119222.229859114][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 0][1575119222.229868174][Client.cpp:276][&td_requests]	End to wait for updates, returning object 0 0x102315530
[ 3][t 0][1575119222.230051279][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 0][1575119222.230060101][Client.cpp:276][&td_requests]	End to wait for updates, returning object 0 0x102310310
[ 3][t 0][1575119222.230185032][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 0][1575119222.230199099][Client.cpp:276][&td_requests]	End to wait for updates, returning object 0 0x10260d930
[ 3][t 0][1575119222.230436087][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 0][1575119222.230444193][Client.cpp:276][&td_requests]	End to wait for updates, returning object 0 0x102613850
[ 3][t 4][1575119222.230470896][Td.cpp:3548][#1][!Td][&td_requests]	Receive request 5: getAuthorizationState {
}
[ 3][t 0][1575119222.230587006][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 0][1575119222.230597258][Client.cpp:276][&td_requests]	End to wait for updates, returning object 0 0x1026131a0
[ 3][t 0][1575119222.230733156][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 0][1575119222.230753183][Client.cpp:276][&td_requests]	End to wait for updates, returning object 0 0x102512550
[ 3][t 0][1575119222.230990171][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 0][1575119222.231011152][Client.cpp:276][&td_requests]	End to wait for updates, returning object 0 0x10242ef60
[ 3][t 0][1575119222.231580973][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 4][1575119222.231589317][RequestActor.h:107][#1][!GetChatHistoryRequest]Receive error for query: [Error : 6 : Chat not found]
[ 3][t 4][1575119222.231620312][Td.cpp:4672][#1][!Td][&td_requests]	Sending result for request 5: authorizationStateReady {
}
[ 3][t 4][1575119222.231651068][Td.cpp:3548][#1][!Td][&td_requests]	Receive request 6: getAuthorizationState {
}
[ 3][t 0][1575119222.231690168][Client.cpp:276][&td_requests]	End to wait for updates, returning object 5 0x102433090
[ 3][t 4][1575119222.231688976][Td.cpp:4687][#1][!Td][&td_requests]	Sending error for request 4: error { code = 6 message = "Chat not found" }
[ 3][t 4][1575119222.231712103][Td.cpp:4672][#1][!Td][&td_requests]	Sending result for request 6: authorizationStateReady {
}
[ 3][t 0][1575119222.231896162][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 0][1575119222.231907129][Client.cpp:276][&td_requests]	End to wait for updates, returning object 4 0x105000120
{ TDLibError: Chat not found
    at toObject (/Users/velten/Entwicklung/telegram-app/node_modules/@airgram/core/utils.js:39:15)
    at Object.<anonymous> (/Users/velten/Entwicklung/telegram-app/src/airgram/response.ts:5:19)
    at step (/Users/velten/Entwicklung/telegram-app/src/airgram/response.ts:33:23)
    at Object.next (/Users/velten/Entwicklung/telegram-app/src/airgram/response.ts:14:53)
    at fulfilled (/Users/velten/Entwicklung/telegram-app/src/airgram/response.ts:5:58)
    at <anonymous> name: 'TDLibError', code: 6 }
[ 3][t 0][1575119222.239633083][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 0][1575119222.239653111][Client.cpp:276][&td_requests]	End to wait for updates, returning object 6 0x1050001e0
[ 3][t 0][1575119222.239850998][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 10.000000
[ 3][t 4][1575119222.287512064][ConfigManager.cpp:509][#1][!Recoverer][&config_recoverer]	ON CONNECTING false
[ 3][t 4][1575119222.287546873][ConfigManager.cpp:689][#1][!Recoverer][&config_recoverer]	Successfully connected
[ 3][t 4][1575119222.287559032][ConfigManager.cpp:753][#1][!Recoverer][&config_recoverer]	Wakeup NEVER
...
```

**Comment by valoricDe** [comment]
Related https://github.com/tdlib/td/issues/791

**Comment by esindger** [comment]
Related to #65
