### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'catch' of undefined

### ISSUE THREAD

**Issue by jeudesprits** [airgram/airgram#48]
**Issue type:**
[v ] question
[v] bug report
[ ] feature request
[ ] documentation issue

```
(node:8257) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'catch' of undefined
    at TdJsonAirgram.Airgram.handleUpdate (/home/node/workspace/node_modules/@airgram/core/dist/Airgram.js:178:66)
    at TdJsonClient.Airgram._this.provider [as handleUpdate] (/home/node/workspace/node_modules/@airgram/core/dist/Airgram.js:82:62)
    at TdJsonClient.<anonymous> (/home/node/workspace/node_modules/airgram/dist/components/TdJsonClient.js:137:55)
    at step (/home/node/workspace/node_modules/airgram/dist/components/TdJsonClient.js:43:23)
    at Object.next (/home/node/workspace/node_modules/airgram/dist/components/TdJsonClient.js:24:53)
    at /home/node/workspace/node_modules/airgram/dist/components/TdJsonClient.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/node/workspace/node_modules/airgram/dist/components/TdJsonClient.js:14:12)
    at TdJsonClient.handleResponse (/home/node/workspace/node_modules/airgram/dist/components/TdJsonClient.js:120:16)
    at TdJsonClient.addToStack (/home/node/workspace/node_modules/airgram/dist/components/TdJsonClient.js:170:22)
```

**Airgram version:**
[ ] latest
[ ] @next
[v] 1.2.0

**libtd version:**
1.4

**Steps to reproduce or a small repository showing the problem:**
```ts
import { Airgram } from 'airgram';
import secrets from './utils/secrets';
const { TG_APP_ID, TG_APP_HASH } = secrets;


// tslint:disable-next-line: no-floating-promises
(async () => {
    try {
        const airgram = new Airgram({
            command: 'lib/libtdjson',
            apiId: Number(TG_APP_ID),
            apiHash: TG_APP_HASH,
            logVerbosityLevel: 2,
        });
          
        await airgram.api.setProfilePhoto({
            photo: {
                _: 'inputFileLocal',
                path: 'time_images/00-00.jpeg',
            }
        });
    } catch (error) {
        console.error(error);
    }
})();
```

**Comment by esindger** [comment]
It happens due TDLib error: `error { code = 401 message = "Initialization parameters are needed: call setTdlibParameters first" }`. This bug will be fixed in the next release. Meantime, as workaround, you can use `Auth` middleware:

```ts
import { Airgram, Auth } from 'airgram';

const airgram = new Airgram({ /* config */ });

// tslint:disable-next-line:no-unused-expression
new Auth(airgram);
          
// tslint:disable-next-line: no-floating-promises
(async () => {
  await airgram.api.setProfilePhoto({ /* parameters */ });
})();
```
