### ISSUE TITLE
Running `getting started`  example

### ISSUE THREAD

**Issue by idkjs** [airgram/airgram#73]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Follow steps from: https://github.com/airgram/airgram/tree/master/examples/getting-started#installation

On `yarn run dev` you get the following error output saying that types for `isError` and `toObject` are not exported among others:

```sh
getting-started [master*]yarn run dev
yarn run v1.21.1
$ DEBUG=airgram* dotenv nodemon --config nodemon.json
[nodemon] 2.0.2
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 96363 to restart
[nodemon] watching dir(s): src/**/*.ts
[nodemon] watching extensions: ts
[nodemon] bind restart -> `echo "[Warning] Remember run yarn run test b4 push to dev branch !"`
[nodemon] starting `node -r ts-node/register ./src/index.ts`
[nodemon] spawning
[nodemon] child pid: 96365
[nodemon] watching 1 file

/Users/prisc_000/Downloads/airgram/node_modules/.pnpm/registry.npmjs.org/ts-node/8.6.1_typescript@3.7.4/node_modules/ts-node/src/index.ts:413
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:1:25 - error TS2305: Module '"../../../../../../../Users/prisc_000/Downloads/airgram/examples/getting-started/node_modules/airgram/src"' has no exported member 'isError'.

1 import { Airgram, Auth, isError, prompt, toObject } from 'airgram'
                          ~~~~~~~
src/index.ts:1:42 - error TS2305: Module '"../../../../../../../Users/prisc_000/Downloads/airgram/examples/getting-started/node_modules/airgram/src"' has no exported member 'toObject'.

1 import { Airgram, Auth, isError, prompt, toObject } from 'airgram'
                                           ~~~~~~~~
src/index.ts:16:9 - error TS2339: Property 'use' does not exist on type 'Airgram'.

16 airgram.use(new Auth({
           ~~~
src/index.ts:23:37 - error TS2339: Property 'api' does not exist on type 'Airgram'.

23   const me = toObject(await airgram.api.getMe())
                                       ~~~
src/index.ts:33:9 - error TS2339: Property 'api' does not exist on type 'Airgram'.

33 airgram.api.setProfilePhoto({
           ~~~
src/index.ts:38:12 - error TS7031: Binding element 'request' implicitly has an 'any' type.

38 }).then(({ request, response }) => {
              ~~~~~~~
src/index.ts:38:21 - error TS7031: Binding element 'response' implicitly has an 'any' type.

38 }).then(({ request, response }) => {
                       ~~~~~~~~
src/index.ts:47:9 - error TS2339: Property 'use' does not exist on type 'Airgram'.

47 airgram.use((ctx, next) => {
           ~~~
src/index.ts:47:14 - error TS7006: Parameter 'ctx' implicitly has an 'any' type.

47 airgram.use((ctx, next) => {
                ~~~
src/index.ts:47:19 - error TS7006: Parameter 'next' implicitly has an 'any' type.

47 airgram.use((ctx, next) => {
                     ~~~~
src/index.ts:55:9 - error TS2339: Property 'on' does not exist on type 'Airgram'.

55 airgram.on('updateNewMessage', async ({ update }, next) => {
           ~~
src/index.ts:55:41 - error TS7031: Binding element 'update' implicitly has an 'any' type.

55 airgram.on('updateNewMessage', async ({ update }, next) => {
                                           ~~~~~~
src/index.ts:55:51 - error TS7006: Parameter 'next' implicitly has an 'any' type.

55 airgram.on('updateNewMessage', async ({ update }, next) => {
                                                     ~~~~

    at createTSError (/Users/prisc_000/Downloads/airgram/node_modules/.pnpm/registry.npmjs.org/ts-node/8.6.1_typescript@3.7.4/node_modules/ts-node/src/index.ts:413:12)
    at reportTSError (/Users/prisc_000/Downloads/airgram/node_modules/.pnpm/registry.npmjs.org/ts-node/8.6.1_typescript@3.7.4/node_modules/ts-node/src/index.ts:417:19)
    at getOutput (/Users/prisc_000/Downloads/airgram/node_modules/.pnpm/registry.npmjs.org/ts-node/8.6.1_typescript@3.7.4/node_modules/ts-node/src/index.ts:522:36)
    at Object.compile (/Users/prisc_000/Downloads/airgram/node_modules/.pnpm/registry.npmjs.org/ts-node/8.6.1_typescript@3.7.4/node_modules/ts-node/src/index.ts:727:32)
    at Module.m._compile (/Users/prisc_000/Downloads/airgram/node_modules/.pnpm/registry.npmjs.org/ts-node/8.6.1_typescript@3.7.4/node_modules/ts-node/src/index.ts:806:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/prisc_000/Downloads/airgram/node_modules/.pnpm/registry.npmjs.org/ts-node/8.6.1_typescript@3.7.4/node_modules/ts-node/src/index.ts:809:12)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
[nodemon] app crashed - waiting for file changes before starting...

```
Thanks for any guidance.

**Comment by esindger** [comment]
I've just cloned and started the getting-started example without errors. Please try to import `isError` and `toObject` from the core package.

```ts
// file:  /examples/getting-started/src/index.ts

import { Airgram, Auth, prompt } from 'airgram'
import { isError, toObject } from '@airgram/core'
```

**Comment by idkjs** [comment]
I will try it again. I got it running here: https://github.com/idkjs/airgram-getting-started. I am new to Airgram and Telegram. Is it expected to that I would build TDLib on my own when using Airgram?

Thanks

**Comment by idkjs** [comment]
I ran the process again using `yarn` instead of `pnpm` and it works without adding `    "@airgram/core": "link:../../packages/core",` to `package.json`. I guess its a `pnpm` thing. Thank you for taking the time @esindger.
